# Generated by Django 5.2.4 on 2025-07-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_downloads_album_likes'),
        ('stls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stl',
            name='albumFk',
        ),
        migrations.AddField(
            model_name='stl',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stl',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='STLOnAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkAlbum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='album.album')),
                ('fkSTL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stls.stl')),
            ],
        ),
    ]
