# Generated by Django 5.2.4 on 2025-07-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stlnormalimage',
            old_name='fkSTl',
            new_name='fkSTL',
        ),
        migrations.RemoveField(
            model_name='stl',
            name='stlUrl',
        ),
        migrations.RemoveField(
            model_name='stlnormalimage',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='stl',
            name='file_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stl',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stlnormalimage',
            name='file_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stlnormalimage',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
