# Generated by Django 5.2.4 on 2025-08-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stls', '0002_rename_fkstl_stlnormalimage_fkstl_remove_stl_stlurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stl',
            name='file_public_id',
        ),
        migrations.RemoveField(
            model_name='stlnormalimage',
            name='file_public_id',
        ),
        migrations.AlterField(
            model_name='stl',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stlnormalimage',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
